vich_uploader:
    db_driver: orm


    mappings: 
        annonce_image:
            uri_prefix: /images/annonce
            upload_destination: '%kernel.project_dir%/public/images/annonce'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
